apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: courageous-python-nodejs-gitops-repository
spec:
  url: https://github.com/redhat-appstudio-qe/courageous-python-nodejs-gitops